### ISSUE TITLE
`api.artsmia.org` missing `utf-8` charaters

### ISSUE THREAD

**Issue by kjell** [artsmia/collection#6]
This is only happening on the external API server (we have 2 that run the same code, one internal and one external). It's probably due to a mis-configuration somewhere.

id | on github | `api.artsmia.org`
------- | ------------ | -----------------------
1555 | [Joan Miró](https://github.com/artsmia/collection/blob/master/objects/1/1555.json) | [Joan Mir](http://api.artsmia.org/objects/1555/full/json)
46277 | [Henri-Charles Guérard; after Édouard Manet](https://github.com/artsmia/collection/blob/c928ee66b029c6e75d802c223088dbfd2480148d/objects/46/46277.json) | [Henri-Charles Gurard](http://api.artsmia.org/objects/46277/full/json)
111860 | [Auguste Louis Lepère](https://github.com/artsmia/collection/tree/6dce5cc4932e59d0b950f6122ca0eb1d5bf08461/objects/111/111860.json) | [Auguste Louis Lepre](http://api.artsmia.org/objects/111860/full/json)
1640 | [Die Brücke](https://github.com/artsmia/collection/tree/6dce5cc4932e59d0b950f6122ca0eb1d5bf08461/objects/1/1640.json) | [Die Brcke (The Bridge)](http://api.artsmia.org/objects/1640/full/json)

https://twitter.com/mdammers/status/640196625298812928

//cc @damnabit

**Comment by kjell** [comment]
It also looks like `external` has a stale data (46277), do we need to flush memcache or redis?

**Comment by damnabit** [comment]
refreshed.
